src/function_invocable.py, src/version.py
Reverts https://github.com/mattian7741/ergo/pull/4 since desired behavior (`filter`ing results) is doable via generator expression.
tested w function:
```
def is_even(payload):
num = payload['num']
if num % 2 == 0:
yield f'{num} is even'
```
and verified after publishing multiple messages only even numbers filtered through.
=> dont filter out none

src/amqp_invoker.py, src/version.py
Now catching base `AMQPError`, since `AMQPConnectionError` was a bit too specific to the `connection` handle.
Also the occasional `ChannelInvalidStateError` inherits from `RuntimeError`.
=> fix(amqp_invoker): better catch-all amqp exception retries

src/amqp_invoker.py, src/version.py
**Context**
Consistently reproduced `InvalidChannelStateError` thrown when `AsyncQueueIteratorContextManager` exits too early for long running consume/publish tasks, >30mins and test with >4hr long tasks. It's possible that although the `connection` was kept alive, there was an underlying issue with the `channel`/`queue` handles that were no longer valid to be reused by the publisher-worker after completing its work in 4hrs.
**Changes**
* Consumer and publisher within event loop attempt to reacquire channel handles prior to each operation
* Avoid using async queue iterator for long running work
https://github.com/mosquito/aio-pika/blob/master/aio_pika/queue.py#L358-L379
* Also removed stubbed `on_error` callback + generally simplified code
**Notes**
* python 3.6 breaks unfortunately bc of …
=> refactor(amqp): Channel pooling for consuming/publishing

src/amqp_invoker.py, src/ergo_cli.py, src/ergo_click.py, src/flask_http_invoker.py, src/function_invocable.py, src/util.py, src/version.py, test/unit/test_util.py
Issue: https://github.com/nautiluslabsco/ergo/issues/23
Separating `error` from `traceback` so that we can at a glance debug several messages in the rabbitmq console. This leverages exception chaining: https://docs.python.org/3/tutorial/errors.html#exception-chaining to grab the originating exception and the traceback information from the same object.
function code that leads to index error:
input message:
error message:
note that `error` now says the more human readable:
`TypeError: 'int' object is not subscriptable`
There are some annoying linting errors that are popping up... think it would be nice if linting wasn't kicked off pre-commit but rather as a blocker to merging. Maybe linting should automatically clean up the code rather than whine about it as well?
=> separate traceback from exception

ergo/version.py
https://github.com/nautiluslabsco/ergo/commit/81a31515c3c397fc430e5e1a235e35ca28581d65 was a breaking change from `0.5.7-alpha`, but some python dependency managers may allow the upgrade from `0.5.7a` to `0.5.8a` as an innocuous change.
=> chore: bump to `0.6.0-alpha`

ergo/config.py, ergo/function_invocable.py, ergo/version.py, test/integration/amqp/test_amqp.py, test/integration/utils/__init__.py, test/integration/utils/amqp.py
I just noticed that ergo 0.6.0a dropped support for custom `args` mapping in configuration yamls. This PR fixes that, and adds an integration test to cover it.
=> correctly apply configuration args mappings

ergo/version.py, setup.py
Quart doesn't pin its jinja2 [requirement](https://github.com/pgjones/quart/blob/main/pyproject.toml#L35), but it raises an ImportError with the latest minor version. So for now, we'll have to pin jinja2 ourselves.
=> pin jinja2 to fix quart import error

ergo/amqp_invoker.py, ergo/message.py, ergo/version.py
We have a mismatch in our transcoding functions, where [message.encodes](https://github.com/nautiluslabsco/ergo/blob/3a4242b3999bc4f9d1356c359beec3e0b10418d4/ergo/message.py#L36) uses json.dumps to serialize outbound payloads, while [message.decodes](https://github.com/nautiluslabsco/ergo/blob/3a4242b3999bc4f9d1356c359beec3e0b10418d4/ergo/message.py#L23) uses the cleverer json**s**.loads to deserialize inbound payloads. The latter will automatically decode iso-formatted date strings into datetime objects, which will break any component that depends on receiving dates as strings.
=> fix json transcoding bug

ergo/context.py, ergo/version.py
Since retrieve doesn't imply index semantics, we should opt for returning `Optional` types so that the caller isn't required to wrap every invocation with a try/except.
=> chore(context): safer retrieve

ergo/amqp_invoker.py, ergo/version.py
- if component's subtopic gets changed, the old binding is left straggling
- this change removes bindings from the component's queue at component shutdown -> when a new component instance is spun up it binds back to a 'clean' queue
[INF-250](https://nautiluslabs.atlassian.net/browse/INF-250?atlOrigin=eyJpIjoiY2U4YzU4ZjIzMmMwNDRiMjgwODgzYmRiZTJkMDczYWIiLCJwIjoiaiJ9)
=> [Inf 250] feat(queue clean up): unbind component at shutdown

ergo/function_invocable.py, ergo/version.py, test/integration/test_amqp/test_argument_binding.py
There’s a bug in FunctionInvocable.assemble_arguments that causes it to fail to bind any data that equals False (e.g. 0) to a handler param.
=> [VOTR-119] fix(falsey argument binding): bind falsey arguments to handler params

ergo/schematic.py, ergo/version.py
currently `ergo graph` doesn't pick up all ergo configs, and it also has a problem with overflowing label text (screenshot because it generates a pdf):
after this change:
=> fix(ergo graph): detect more ergo configs; fixed overlapping labels by allowing nodes to resize themselves; put topics in boxes

.circleci/config.yml, ergo/amqp_invoker.py, ergo/version.py, test/integration/utils/__init__.py
I'm seeing two potential causes for test flakiness:
1. The test runner is trying to gracefully shutdown ergo subprocs, which tends to timeout for a particular test (`test_fibonacci`) that generates a lot of amqp messages. But there's no reason to be graceful here, since we're tearing everything down anyways.
2. Ergo's amqp consumer shutdown sequence uses a function that was added in python 3.8, which periodically breaks the 3.7 test runner. I replaced it with something 3.7 compatible.
=> [VOTR-185] fix(tests): fix test flakiness

ergo/amqp_invoker.py, ergo/version.py
This PR reverts the changes in https://github.com/nautiluslabsco/ergo/pull/86, which don't seem to be working as intended. That change was recently installed by the routes-generator staging consumers, which have since begun consistently falling into a [connection error loop](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Fecs$252Froutes-generator-staging/log-events/ecs$252Froutes$252F626d49602bc443909c2083497c6fe8f8). Meanwhile, the broker is reporting hundreds of consumer bindings on their [component queue](https://b-4578b105-1d2d-4ecf-8f90-63ff45aa4fbc.mq.us-east-1.amazonaws.com/#/queues/%2F/routes%3Ahandler.py%3Agenerate_routes). I don't have a theory for the reverted change could be failing, but I don't see any other commits …
=> [VOTR-185] autodelete component queues

ergo/amqp_invoker.py, ergo/function_invocable.py, ergo/message.py, ergo/version.py, test/integration/start_rabbitmq_broker.py, test/integration/test_amqp/test_extra_error_info.py, test/integration/utils/amqp.py
this makes error information available to components that consume from error queues
used in https://github.com/nautiluslabsco/qed/pull/749 more specifically https://github.com/nautiluslabsco/nl-qed-util/pull/36
=> feat: TTV-41 expose error information in ergo message

ergo/version.py, setup.py
while working on https://github.com/nautiluslabsco/pearls/pull/31 for https://github.com/nautiluslabsco/pearls/security/dependabot/3 i discovered that ergo needs retry, which needs py
```
% pip show retry
Name: retry
Version: 0.9.2
Summary: Easy to use retry decorator.
Home-page: https://github.com/invl/retry
Author: invl
Author-email: invlpg@gmail.com
License: Apache License 2.0
Location: /Users/xian/.pyenv/versions/pearls/lib/python3.9/site-packages
Requires: decorator, py
Required-by: ergo
```
but i can't find anywhere that uses retry, so opting to remove it
=> chore: removed retry dependency

ergo/amqp_invoker.py, ergo/version.py
the correct spelling seems to be auto_delete
sources:
https://docs.celeryq.dev/projects/kombu/en/stable/reference/kombu.html#queue
https://github.com/nautiluslabsco/ergo/blob/b7805bcf1e411df461197432783eae8ad5cb37aa/ergo/amqp_invoker.py#L68
=> fix: changed autodelete to auto_delete

.circleci/config.yml, Makefile
in https://github.com/nautiluslabsco/ergo/pull/108 unrelated tests which passed last time are now failing
digging deeper, we see failures that look like
```
File "/home/circleci/project/venv/lib/python3.10/site-packages/hypercorn/config.py", line 261, in _create_sockets
sock.bind(binding)
PermissionError: [Errno 13] Permission denied
```
it is trying to use localhost port 80, so maybe there was a policy change in circleci to no longer allow that... this pr runs the test with sudo to get around that
references:
https://stackoverflow.com/questions/8633461/how-to-keep-environment-variables-when-using-sudo
https://askubuntu.com/questions/234758/how-to-use-a-python-virtualenv-with-sudo
https://stackoverflow.com/questions/28890634/how-to-get-a-shell-environment-variable-in-a-makefile
=> chore: try to resolve current test failures by running with sudo

ergo/amqp_invoker.py, ergo/version.py
in https://github.com/nautiluslabsco/ergo/pull/107 i fixed a typo and set component queues to auto delete 
but after using that a bit, i have changed my mind; reasoning below
firstly, according to [the documentation](https://www.rabbitmq.com/queues.html#:~:text=An%20auto%2Ddelete%20queue%20will,TCP%20connection%20with%20the%20server), if so configured, these queues will be deleted when the consumer disconnects... i could not find anything on the internet that says the queue has to be empty... so it deletes the queue even if it's not empty, as long as the consumer has disconnected
also it's difficult to update an existing component to ergo 0.11.3 because:
* queue already exists
* we upgrade to 0.11.3 and deploy
* we try to recreate the queue with auto delete
* this fails because there is …
=> chore: don't auto delete component queue

.circleci/config.yml
[GEN-232](https://nautiluslabs.atlassian.net/browse/GEN-232)
i used this as reference for where to get the credentials: https://github.com/nautiluslabsco/nlpy/blob/88446fdc1758727b31ff688e9e33cf8edf2a2939/.circleci/config.yml
the environment variables are here: https://app.circleci.com/settings/organization/github/nautiluslabsco/contexts/57619c54-647c-4d27-8093-cf4397b8e781
twine documentation: https://twine.readthedocs.io/en/stable/#twine-upload
not tested at all
my plan after merge is to remove the 0.13.0 auto-released tags and releases, re-tag 0.12.0, and re-release
[GEN-232]: https://nautiluslabs.atlassian.net/browse/GEN-232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: GEN-232 temporarily publish to internal pypi

.circleci/config.yml
following up on https://github.com/nautiluslabsco/ergo/pull/110
i thought it was already configured to use this context because it is named default context, but it wasn't
copied from https://github.com/nautiluslabsco/nlpy/blob/88446fdc1758727b31ff688e9e33cf8edf2a2939/.circleci/config.yml#L7
=> chore: GEN-232 added default context to circleci config
